### ISSUE TITLE
Checkboxes

### ISSUE THREAD

**Issue by ryan4835** [m-roskrow/louis-meals#1]
Where is  *Checkboxes* broooooo?

![image](https://user-images.githubusercontent.com/19718120/111655607-b486a580-8801-11eb-8c0d-e467d5a1a9a8.png)

and cheflou

**Comment by ryan4835** [comment]
> Where is _Checkboxes_ broooooo?
> 
> ![image](https://user-images.githubusercontent.com/19718120/111655607-b486a580-8801-11eb-8c0d-e467d5a1a9a8.png)
> 
> and cheflou

also this is my account

**Comment by m-roskrow** [comment]
added checkboxes xoxoxox
